import request from './request'

export const createPost = (formData) => request.post('/post', formData, { headers: { 'Content-Type': 'multipart/form-data' } })
export const getPostList = (page = 1, size = 10) => request.get('/post/list', { params: { page, size } })
export const getPostById = (id) => request.get(`/post/${id}`)
export const deletePost = (id) => request.delete(`/post/${id}`)
export const getReviewTargets = (postId) => request.get(`/post/${postId}/review-targets`)
export const createReviewTarget = (postId, data) => request.post(`/post/${postId}/review-target`, data)
export const getReviewTargetById = (id) => request.get(`/post/review-target/${id}`)
export const getReviewTargetStats = (id) => request.get(`/post/review-target/${id}/stats`)
export const addComment = (targetId, data) => request.post(`/post/review-target/${targetId}/comment`, data)
export const getComments = (targetId) => request.get(`/post/review-target/${targetId}/comments`)
export const deleteComment = (id) => request.delete(`/post/comment/${id}`)
export const deleteReviewTarget = (id) => request.delete(`/post/review-target/${id}`)
export const getPostStats = (id) => request.get(`/post/${id}/stats`)
export const getPostsByTag = (tag, page = 1, size = 10) => request.get('/post/list/by-tag', { params: { tag, page, size } })
export const getPostsRanking = (sort = 'hot', page = 1, size = 20) => request.get('/post/list/ranking', { params: { sort, page, size } })
export const getPersonalized = (previousIds) => request.get('/post/list/personalized', { params: { previousIds } })
export const search = (keyword) => request.get('/post/search', { params: { keyword } })
export const getUserPostsMe = () => request.get('/post/user/posts')
export const getUserCommentsMe = () => request.get('/post/user/comments')
export const getUserReviewTargetsMe = () => request.get('/post/user/review-targets')
export const sharePost = (id, shareType) => request.post(`/post/${id}/share`, { shareType })
