-- 修复数据库表注释（UTF-8编码）

ALTER TABLE user
  MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT COMMENT '用户ID',
  MODIFY COLUMN username VARCHAR(50) NOT NULL COMMENT '用户名',
  MODIFY COLUMN password VARCHAR(255) NOT NULL COMMENT '密码哈希值',
  MODIFY COLUMN role VARCHAR(20) DEFAULT 'user' COMMENT '角色: user/admin/super_admin',
  MODIFY COLUMN status VARCHAR(20) DEFAULT 'active' COMMENT '状态: active/muted',
  MODIFY COLUMN avatar VARCHAR(500) DEFAULT NULL COMMENT '头像URL',
  MODIFY COLUMN signature VARCHAR(200) DEFAULT NULL COMMENT '个性签名',
  MODIFY COLUMN bio VARCHAR(500) DEFAULT NULL COMMENT '个人简介',
  MODIFY COLUMN gender TINYINT DEFAULT 0 COMMENT '性别: 0=未知, 1=男, 2=女',
  MODIFY COLUMN campus VARCHAR(100) DEFAULT NULL COMMENT '院系/校区',
  MODIFY COLUMN created_at DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '注册时间';

ALTER TABLE post
  MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT COMMENT '帖子ID',
  MODIFY COLUMN user_id BIGINT NOT NULL COMMENT '发布者ID',
  MODIFY COLUMN title VARCHAR(200) NOT NULL COMMENT '标题',
  MODIFY COLUMN content TEXT NOT NULL COMMENT '内容',
  MODIFY COLUMN created_at DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '发布时间',
  MODIFY COLUMN updated_at DATETIME DEFAULT NULL COMMENT '更新时间',
  MODIFY COLUMN image_url VARCHAR(500) DEFAULT NULL COMMENT '图片URL',
  MODIFY COLUMN tag VARCHAR(50) DEFAULT NULL COMMENT '分类标签',
  MODIFY COLUMN view_count INT DEFAULT 0 COMMENT '浏览量',
  MODIFY COLUMN like_count INT DEFAULT 0 COMMENT '点赞数',
  MODIFY COLUMN favorite_count INT DEFAULT 0 COMMENT '收藏数';

ALTER TABLE like_record
  MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT COMMENT '记录ID',
  MODIFY COLUMN user_id BIGINT NOT NULL COMMENT '用户ID',
  MODIFY COLUMN target_type VARCHAR(20) NOT NULL COMMENT '目标类型: post/comment',
  MODIFY COLUMN target_id BIGINT NOT NULL COMMENT '目标ID',
  MODIFY COLUMN created_at DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '点赞时间';

ALTER TABLE favorite
  MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT COMMENT '记录ID',
  MODIFY COLUMN user_id BIGINT NOT NULL COMMENT '用户ID',
  MODIFY COLUMN post_id BIGINT NOT NULL COMMENT '帖子ID',
  MODIFY COLUMN created_at DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '收藏时间';

ALTER TABLE follow
  MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT COMMENT '记录ID',
  MODIFY COLUMN follower_id BIGINT NOT NULL COMMENT '关注者ID',
  MODIFY COLUMN following_id BIGINT NOT NULL COMMENT '被关注者ID',
  MODIFY COLUMN created_at DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '关注时间';

ALTER TABLE message
  MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT COMMENT '消息ID',
  MODIFY COLUMN sender_id BIGINT NOT NULL COMMENT '发送者ID',
  MODIFY COLUMN receiver_id BIGINT NOT NULL COMMENT '接收者ID',
  MODIFY COLUMN content TEXT NOT NULL COMMENT '消息内容',
  MODIFY COLUMN is_read TINYINT(1) DEFAULT 0 COMMENT '是否已读: 0=未读, 1=已读',
  MODIFY COLUMN created_at DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '发送时间';

ALTER TABLE notification
  MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT COMMENT '通知ID',
  MODIFY COLUMN user_id BIGINT NOT NULL COMMENT '接收用户ID',
  MODIFY COLUMN from_user_id BIGINT DEFAULT NULL COMMENT '触发用户ID',
  MODIFY COLUMN type VARCHAR(30) NOT NULL COMMENT '类型: like/comment/follow/system',
  MODIFY COLUMN target_type VARCHAR(20) DEFAULT NULL COMMENT '目标类型: post/comment',
  MODIFY COLUMN target_id BIGINT DEFAULT NULL COMMENT '目标ID',
  MODIFY COLUMN content VARCHAR(500) DEFAULT NULL COMMENT '通知内容',
  MODIFY COLUMN is_read TINYINT(1) DEFAULT 0 COMMENT '是否已读: 0=未读, 1=已读',
  MODIFY COLUMN created_at DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间';

ALTER TABLE share_record
  MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT COMMENT '记录ID',
  MODIFY COLUMN user_id BIGINT DEFAULT NULL COMMENT '用户ID',
  MODIFY COLUMN post_id BIGINT NOT NULL COMMENT '帖子ID',
  MODIFY COLUMN share_type VARCHAR(20) NOT NULL COMMENT '分享方式: link/wechat/qq',
  MODIFY COLUMN created_at DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '分享时间';
